# coding=utf-8
command_eng = {
    0: "Increase the illumination",
    1: "Decrease the illumination",
    2: "Increase the height",
    3: "Decrease the height",
    4: "Increase the inclination",
    5: "Decrease the inclination",
    6: "Bring me the gun screwdriver",
    7: "Take the gun screwdriver",
    8: "Bring me the elbow screwdriver",
    9: "Take the elbow screwdriver",
    10: "Bring me the hammer",
    11: "Take the hammer",
    12: "Bring me the screwdriver",
    13: "Take the screwdriver",
    14: "Bring me the lever",
    15: "Take the lever",
    16: "Come here",
    17: "Go",
    18: "Start",
    19: "Stop",
    20: "Move to the right",
    21: "Move to the left",
    22: "Move up",
    23: "Move down",
    24: "Move forward",
    25: "Move backward",
    26: "Bring me the mostrina comandi",
    27: "Take the mostrina comandi"
}

command_ita = {
    0: "Devo aprire la finestra?",
    1: "",
    2: "",
    3: "",
    4: "",
    5: "",
    6: "Hai controllato la batteria?",
    7: "",
    8: "",
    9: "",
    10: "Attento alle dita",
    11: "Vuoi anche i chiodi?",
    12: "",
    13: "Lo prendo subito",
    14: "",
    15: "",
    16: "Arrivo",
    17: "",
    18: "Cominciamo",
    19: "",
    20: "",
    21: "",
    22: "",
    23: "",
    24: "Ok",
    25: "Non mettermi lo sgambetto",
    26: "",
    27: ""
}