command_eng = {
    0: "Increase the illumination",
    1: "Decrease the illumination",
    2: "Increase the height",
    3: "Decrease the height",
    4: "Increase the inclination",
    5: "Decrease the inclination",
    6: "Bring me the gun screwdriver",
    7: "Take the gun screwdriver",
    8: "Bring me the elbow screwdriver",
    9: "Take the elbow screwdriver",
    10: "Bring me the hammer",
    11: "Take the hammer",
    12: "Bring me the screwdriver",
    13: "Take the screwdriver",
    14: "Bring me the lever",
    15: "Take the lever",
    16: "Come here",
    17: "Go",
    18: "Start",
    19: "Stop",
    20: "Move to the right",
    21: "Move to the left",
    22: "Move up",
    23: "Move down",
    24: "Move forward",
    25: "Move backward",
    26: "Bring me the mostrina comandi",
    27: "Take the mostrina comandi"
}

command_ita = {
    0: "Più luce",
    1: "Meno luce",
    2: "Più alto",
    3: "Più basso",
    4: "Più inclinato",
    5: "Meno inclinato",
    6: "Portami l'avvitatore elettrico",
    7: "Prendi l'avvitatore elettrico",
    8: "Portami l'avvitatore a gomito",
    9: "Prendi l'avvitatore a gomito",
    10: "Portami il martello",
    11: "Prendi il martello",
    12: "Portami il cacciavite",
    13: "Prendi il cacciavite",
    14: "Portami la leva",
    15: "Prendi la leva",
    16: "Vieni",
    17: "Libero",
    18: "Start",
    19: "Stop",
    20: "Vai a destra",
    21: "Vai a sinistra",
    22: "Vai su",
    23: "Vai giù",
    24: "Vai avanti",
    25: "Vai indietro",
    26: "Portami la mostrina comandi",
    27: "Prendi la mostrina comandi"
}